language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
before_install:
- pip install -U pip setuptools pytest wheel
install:
- python setup.py install
script:
- python setup.py test --addopts -v
deploy:
  provider: pypi
  user: hroncok
  password:
    secure: o4/nJOCa5p1OsGH9bxFVarepHLZyql3Zoofg3xhIZ8ABYxR7ealsldw5oxlmQyj3LWnaIeOrG/81dhN57JesCJ78xkyPaPEtolBsxWrclbdE7+DUZRBOA6WvzeIvy6uFb7AGrCuquPhCdeIlFZlGyoiHfASRVRjvRiaqf35VQ8nw1AWs6SFLWW3HEjjcuBi6BUyIsIlotevpQY1kwWjypB9mie5efVk0DJlDKn5OUz7SDOjTf52/j4ezFFi+fdvv0MBKYvb95M+IZWdUTh7oF5yloNUBQDZxBFQ2eq0FtGw3im6iS+1jJWlKlY3XJDbUri3JvrRhTKf2NQEiDsqrkEth6/YYh4KDdZLxvyt0PhdehogpKWtVFvZN7q/88H5TmQpcKZGLAC9MgfeLB9/yFswGJ2yQQkJb34JGZz1cCdl9xnf8zV6/o84dP7j9qZi32YpopA9c8JbncxwwpJSIyOzpYjGPi6d+fR0gPOv11H6wHb+YhOnz2zaP0DOiJ2X/c0uo30dO9gFUXZovqe0jKTaASsLQvwYu2Deghd9sD3p94YH51FWtrs0xGPey6Tty/ay7uNPOPBEnOPZLvC6USqxQFJDZ/EDOxZDiyr+9vBML/jXpDLPEKYPyzbxKqdtsndsLofn2GTBsJUwasQ2sH5C9vW6ss760XvZIAM2Ie1s=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: hroncok/kojistatus
